/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/plugin-main.ts
var plugin_main_exports = {};
__export(plugin_main_exports, {
  default: () => MetadataLinkParserPlugin
});
module.exports = __toCommonJS(plugin_main_exports);
var import_obsidian5 = require("obsidian");

// src/parse-metadata-link.ts
var import_obsidian3 = require("obsidian");

// src/ReadItLaterStubs.ts
var import_obsidian = require("obsidian");
var NoteService = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Create a note from content (URL or text)
   * This is a simplified implementation - the real ReadItLater plugin
   * provides much more sophisticated parsing and formatting
   */
  async createNote(content) {
    try {
      const isUrl = content.match(/^https?:\/\//);
      if (isUrl) {
        await this.createNoteFromUrl(content);
      } else {
        await this.createNoteFromText(content);
      }
    } catch (error) {
      console.error("Error creating note:", error);
      new import_obsidian.Notice("Failed to create note from content");
    }
  }
  /**
   * Create multiple notes from batch content
   * Expects content to be delimited by newlines
   */
  async createNotesFromBatch(contentBatch) {
    const items = contentBatch.split("\n").filter((line) => line.trim());
    for (const item of items) {
      await this.createNote(item.trim());
    }
  }
  /**
   * Insert content at cursor position in editor
   */
  async insertContentAtEditorCursorPosition(content, editor) {
    try {
      const isUrl = content.match(/^https?:\/\//);
      if (isUrl) {
        const articleContent = await this.fetchArticleContent(content);
        if (articleContent) {
          editor.replaceSelection(articleContent);
        } else {
          editor.replaceSelection(`[Article](${content})

Failed to fetch content.`);
        }
      } else {
        editor.replaceSelection(content);
      }
    } catch (error) {
      console.error("Error inserting content:", error);
      new import_obsidian.Notice("Failed to insert content");
    }
  }
  /**
   * Get markdown content from URL without creating a note
   * This is used when we want to append parsed content to existing files
   */
  async getMarkdownContent(content) {
    try {
      const isUrl = content.match(/^https?:\/\//);
      if (isUrl) {
        return await this.fetchArticleContent(content);
      } else {
        return content;
      }
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : "Unknown error";
      console.error("Error getting markdown content:", errorMessage);
      return null;
    }
  }
  /**
   * Create a note from a URL by fetching its content
   */
  async createNoteFromUrl(url) {
    new import_obsidian.Notice(`Fetching content from: ${url}`);
    const content = await this.fetchArticleContent(url);
    if (!content) {
      new import_obsidian.Notice("Failed to fetch article content");
      return;
    }
    const filename = this.generateFilenameFromUrl(url);
    const notePath = `${filename}.md`;
    await this.app.vault.create(notePath, content);
    new import_obsidian.Notice(`Created note: ${filename}`);
  }
  /**
   * Create a note from plain text
   */
  async createNoteFromText(text) {
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const filename = `Note-${timestamp}`;
    const notePath = `${filename}.md`;
    await this.app.vault.create(notePath, text);
    new import_obsidian.Notice(`Created note: ${filename}`);
  }
  /**
   * Fetch article content from URL
   */
  async fetchArticleContent(url) {
    try {
      const response = await fetch(url);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const html = await response.text();
      const plainText = this.extractTextFromHtml(html);
      return `# Article from ${url}

**Source:** ${url}

${plainText}`;
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : "Unknown error";
      console.error(`Error fetching article from ${url}:`, errorMessage);
      return null;
    }
  }
  /**
   * Extract text content from HTML
   */
  extractTextFromHtml(html) {
    let text = html.replace(/<script[^>]*>([\s\S]*?)<\/script>/gi, "");
    text = text.replace(/<style[^>]*>([\s\S]*?)<\/style>/gi, "");
    text = text.replace(/<[^>]+>/g, " ");
    text = text.replace(/&nbsp;/g, " ");
    text = text.replace(/&quot;/g, '"');
    text = text.replace(/&apos;/g, "'");
    text = text.replace(/&amp;/g, "&");
    text = text.replace(/&lt;/g, "<");
    text = text.replace(/&gt;/g, ">");
    text = text.replace(/\s+/g, " ");
    text = text.trim();
    const maxLength = 5e4;
    if (text.length > maxLength) {
      text = text.substring(0, maxLength) + "\n\n[Content truncated...]";
    }
    return text;
  }
  /**
   * Generate a valid filename from a URL
   */
  generateFilenameFromUrl(url) {
    try {
      const urlObj = new URL(url);
      let filename = urlObj.hostname.replace(/^www\./, "") + urlObj.pathname;
      filename = filename.replace(/[^a-zA-Z0-9-_]/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "").substring(0, 100);
      return filename || "article";
    } catch (e) {
      return `article-${Date.now()}`;
    }
  }
};
var ReadItLaterApi = class {
  constructor(noteService) {
    this.noteService = noteService;
  }
  /**
   * Create single note from provided input (URL or text)
   */
  async processContent(content) {
    await this.noteService.createNote(content);
  }
  /**
   * Create multiple notes from provided input delimited by newlines
   */
  async processContentBatch(contentBatch) {
    await this.noteService.createNotesFromBatch(contentBatch);
  }
  /**
   * Insert processed content from input at current position in editor
   */
  async insertContentAtEditorCursorPosition(content, editor) {
    await this.noteService.insertContentAtEditorCursorPosition(content, editor);
  }
  /**
   * Get parsed markdown content from URL without creating a note
   * This is used for appending to existing files
   */
  async getMarkdownContent(content) {
    return await this.noteService.getMarkdownContent(content);
  }
};
function isReadItLaterInstalled(app) {
  var _a, _b;
  return ((_b = (_a = app.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b["obsidian-read-it-later"]) !== void 0;
}
var EnhancedNoteService = class extends NoteService {
  constructor(app, readItLaterNoteService) {
    super(app);
    this.readItLaterNoteService = readItLaterNoteService;
  }
  /**
   * Override getMarkdownContent to use ReadItLater's parser when available
   */
  async getMarkdownContent(content) {
    if (this.readItLaterNoteService) {
      try {
        if (this.readItLaterNoteService.makeNote) {
          const note = await this.readItLaterNoteService.makeNote(content);
          if (note && note.content) {
            console.log("Using ReadItLater parser for markdown generation");
            return note.content;
          }
        }
      } catch (error) {
        console.warn("Failed to use ReadItLater parser, falling back to basic parsing:", error);
      }
    }
    console.log("Using basic HTML parser for markdown generation");
    return await super.getMarkdownContent(content);
  }
  /**
   * Use ReadItLater's createNote if available
   */
  async createNote(content) {
    if (this.readItLaterNoteService) {
      try {
        await this.readItLaterNoteService.createNote(content);
        return;
      } catch (error) {
        console.warn("Failed to use ReadItLater createNote:", error);
      }
    }
    await super.createNote(content);
  }
  /**
   * Use ReadItLater's batch processing if available
   */
  async createNotesFromBatch(contentBatch) {
    if (this.readItLaterNoteService) {
      try {
        await this.readItLaterNoteService.createNotesFromBatch(contentBatch);
        return;
      } catch (error) {
        console.warn("Failed to use ReadItLater batch processing:", error);
      }
    }
    await super.createNotesFromBatch(contentBatch);
  }
};
function getNoteService(app) {
  if (isReadItLaterInstalled(app)) {
    try {
      const readItLaterPlugin = app.plugins.plugins["obsidian-read-it-later"];
      if (readItLaterPlugin.noteService) {
        console.log("Using ReadItLater plugin with enhanced wrapper");
        return new EnhancedNoteService(app, readItLaterPlugin.noteService);
      }
    } catch (error) {
      console.warn("ReadItLater plugin found but could not access NoteService:", error);
    }
  }
  console.log("Using stub NoteService implementation");
  return new NoteService(app);
}

// src/url-transformer/url-transformer.ts
var import_obsidian2 = require("obsidian");
var TEST_URL = "https://example.com/test";
var UrlTransformer = class {
  constructor(cacheTtlMinutes = 5, timeoutMs = 5e3) {
    this.healthCache = {};
    this.cacheTtlMs = cacheTtlMinutes * 60 * 1e3;
    this.timeoutMs = timeoutMs;
  }
  matchesPattern(url, pattern) {
    try {
      const urlObj = new URL(url);
      const hostname = urlObj.hostname;
      if (pattern === "*") {
        return true;
      }
      if (pattern.startsWith("*.")) {
        const domain = pattern.substring(2);
        return hostname === domain || hostname.endsWith("." + domain);
      }
      return hostname === pattern;
    } catch (error) {
      console.error("Error matching pattern:", error);
      return false;
    }
  }
  matchesRule(url, rule) {
    if (!rule.enabled) {
      return false;
    }
    const included = rule.matchers.some((matcher) => this.matchesPattern(url, matcher));
    if (!included) {
      return false;
    }
    if (rule.excludeMatchers && rule.excludeMatchers.length > 0) {
      const excluded = rule.excludeMatchers.some((matcher) => this.matchesPattern(url, matcher));
      if (excluded) {
        return false;
      }
    }
    return true;
  }
  findMatchingRules(url, rules) {
    return rules.filter((rule) => this.matchesRule(url, rule));
  }
  applyTransformation(url, rule) {
    const template = rule.template;
    switch (rule.transformationType) {
      case "prefix":
        return template.replace("{url}", url);
      case "path-extraction":
        try {
          const urlObj = new URL(url);
          const path = urlObj.pathname + urlObj.search + urlObj.hash;
          const domain = urlObj.hostname;
          return template.replace("{url}", url).replace("{path}", path).replace("{domain}", domain);
        } catch (error) {
          console.error("Error extracting path:", error);
          return template.replace("{url}", url);
        }
      default:
        return template.replace("{url}", url);
    }
  }
  extractProxyBaseUrl(transformedUrl) {
    try {
      const urlObj = new URL(transformedUrl);
      return `${urlObj.protocol}//${urlObj.hostname}`;
    } catch (error) {
      console.error("Error extracting proxy base URL:", error);
      return transformedUrl;
    }
  }
  isCacheValid(proxyBaseUrl) {
    const cached = this.healthCache[proxyBaseUrl];
    if (!cached) {
      return false;
    }
    const now = Date.now();
    return now - cached.lastChecked < this.cacheTtlMs;
  }
  async checkProxyHealthWithTimeout(url) {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.timeoutMs);
    try {
      const response = await (0, import_obsidian2.requestUrl)({
        url,
        method: "HEAD"
      });
      clearTimeout(timeoutId);
      return response.status >= 200 && response.status < 400;
    } catch (error) {
      clearTimeout(timeoutId);
      console.warn(`Proxy health check failed for ${url}:`, error);
      return false;
    }
  }
  async checkProxyHealth(proxyBaseUrl, rule) {
    if (this.isCacheValid(proxyBaseUrl)) {
      return this.healthCache[proxyBaseUrl].healthy;
    }
    const testTransformedUrl = this.applyTransformation(TEST_URL, rule);
    let healthy = await this.checkProxyHealthWithTimeout(testTransformedUrl);
    if (!healthy) {
      healthy = await this.checkProxyHealthWithTimeout(proxyBaseUrl);
    }
    this.healthCache[proxyBaseUrl] = {
      healthy,
      lastChecked: Date.now()
    };
    return healthy;
  }
  async transformUrl(url, rules) {
    const matchingRules = this.findMatchingRules(url, rules);
    if (matchingRules.length === 0) {
      return {
        transformedUrl: url,
        originalUrl: url,
        proxyHealthy: true
      };
    }
    const firstRule = matchingRules[0];
    const transformedUrl = this.applyTransformation(url, firstRule);
    return {
      transformedUrl,
      originalUrl: url,
      appliedRule: firstRule.name,
      proxyHealthy: true
    };
  }
  /**
   * Transform URL with health-check validation.
   * Tries each matching rule in list order; skips unhealthy proxies.
   * Falls back to next matching rule when enableFallback is true.
   */
  async transformUrlWithHealthCheck(url, rules, enableFallback = false) {
    const matchingRules = this.findMatchingRules(url, rules);
    if (matchingRules.length === 0) {
      return {
        transformedUrl: url,
        originalUrl: url,
        proxyHealthy: true
      };
    }
    const failedRules = [];
    const rulesToTry = enableFallback ? matchingRules : [matchingRules[0]];
    for (const rule of rulesToTry) {
      const transformedUrl = this.applyTransformation(url, rule);
      const proxyBaseUrl = this.extractProxyBaseUrl(transformedUrl);
      const isHealthy = await this.checkProxyHealth(proxyBaseUrl, rule);
      if (isHealthy) {
        if (failedRules.length > 0) {
          console.log(`Proxy fallback: "${failedRules.join('", "')}" failed, using "${rule.name}"`);
        }
        return {
          transformedUrl,
          originalUrl: url,
          appliedRule: rule.name,
          proxyHealthy: true
        };
      }
      failedRules.push(rule.name);
      console.warn(`Proxy "${rule.name}" is unhealthy for ${url}${enableFallback ? ", trying next..." : ""}`);
    }
    return {
      transformedUrl: null,
      originalUrl: url,
      appliedRule: failedRules.join(", "),
      proxyHealthy: false,
      error: `All matching proxy services are currently unavailable: ${failedRules.join(", ")}`
    };
  }
  clearCache() {
    this.healthCache = {};
  }
  async testAllProxies(rules) {
    const results = /* @__PURE__ */ new Map();
    for (const rule of rules) {
      if (!rule.enabled) {
        continue;
      }
      const testUrl = this.applyTransformation(TEST_URL, rule);
      const proxyBaseUrl = this.extractProxyBaseUrl(testUrl);
      delete this.healthCache[proxyBaseUrl];
      const healthy = await this.checkProxyHealth(proxyBaseUrl, rule);
      results.set(rule.name, healthy);
    }
    return results;
  }
};

// src/parse-metadata-link.ts
var MetadataLinkParser = class {
  constructor(app, noteService) {
    this.urlTransformer = null;
    this.transformationConfig = null;
    this.app = app;
    this.readItLaterApi = new ReadItLaterApi(noteService);
  }
  setTransformationConfig(config) {
    this.transformationConfig = config;
    this.urlTransformer = new UrlTransformer(
      config.proxyHealthCacheTtlMinutes,
      config.proxyHealthTimeoutMs
    );
  }
  /**
   * Serialize a value to YAML format
   * Handles arrays, strings with special characters, and other types
   */
  serializeYamlValue(key, value) {
    if (Array.isArray(value)) {
      if (value.length === 0) {
        return `${key}: []`;
      }
      const items = value.map((item) => `  - ${item}`).join("\n");
      return `${key}:
${items}`;
    }
    if (typeof value === "string" && (value.includes(":") || value.includes("#") || value.includes("\n"))) {
      return `${key}: "${value.replace(/"/g, '\\"')}"`;
    }
    if (typeof value === "boolean" || typeof value === "number") {
      return `${key}: ${value}`;
    }
    if (value === null || value === void 0) {
      return `${key}: null`;
    }
    return `${key}: ${value}`;
  }
  /**
   * Check if a file has already been processed
   * Looks for 'article_processed: true' in frontmatter
   */
  async isFileProcessed(file) {
    try {
      const content = await this.app.vault.read(file);
      const frontMatterInfo = (0, import_obsidian3.getFrontMatterInfo)(content);
      if (!frontMatterInfo.exists) {
        return false;
      }
      const frontmatterText = content.substring(
        frontMatterInfo.from,
        frontMatterInfo.to
      );
      const frontmatter = (0, import_obsidian3.parseYaml)(frontmatterText);
      return (frontmatter == null ? void 0 : frontmatter.article_processed) === true;
    } catch (error) {
      console.error("Error checking if file is processed:", error);
      return false;
    }
  }
  /**
   * Mark a file as processed by adding 'article_processed: true' to frontmatter
   */
  async markFileAsProcessed(file) {
    var _a;
    try {
      const content = await this.app.vault.read(file);
      const frontMatterInfo = (0, import_obsidian3.getFrontMatterInfo)(content);
      if (!frontMatterInfo.exists) {
        const newContent = `---
article_processed: true
---

${content}`;
        await this.app.vault.modify(file, newContent);
      } else {
        const frontmatterText = content.substring(
          frontMatterInfo.from,
          frontMatterInfo.to
        );
        const frontmatter = (0, import_obsidian3.parseYaml)(frontmatterText);
        if ((frontmatter == null ? void 0 : frontmatter.article_processed) !== true) {
          const updatedFrontmatter = { ...frontmatter, article_processed: true };
          const yamlLines = Object.entries(updatedFrontmatter).map(([key, value]) => this.serializeYamlValue(key, value));
          const newFrontmatter = `---
${yamlLines.join("\n")}
---
`;
          const afterFrontmatter = content.substring((_a = frontMatterInfo.contentStart) != null ? _a : frontMatterInfo.to);
          const newContent = newFrontmatter + afterFrontmatter;
          await this.app.vault.modify(file, newContent);
        }
      }
    } catch (error) {
      console.error("Error marking file as processed:", error);
    }
  }
  /**
   * Extract URL from file's frontmatter metadata
   * Supports both 'url', 'link', and 'source' fields
   */
  extractUrlFromFrontmatter(fileContent) {
    const frontMatterInfo = (0, import_obsidian3.getFrontMatterInfo)(fileContent);
    if (!frontMatterInfo.exists) {
      return null;
    }
    const frontmatterText = fileContent.substring(
      frontMatterInfo.from,
      frontMatterInfo.to
    );
    try {
      const frontmatter = (0, import_obsidian3.parseYaml)(frontmatterText);
      const urlFields = ["url", "link", "source", "web_url", "article_url"];
      for (const field of urlFields) {
        if (frontmatter && frontmatter[field]) {
          return frontmatter[field];
        }
      }
    } catch (error) {
      console.error("Error extracting URL from frontmatter:", error);
    }
    return null;
  }
  /**
   * Extract URL from markdown content (first link found)
   */
  extractUrlFromContent(content) {
    const markdownLinkRegex = /\[([^\]]+)\]\(([^)]+)\)/;
    const match = content.match(markdownLinkRegex);
    if (match && match[2]) {
      return match[2];
    }
    const urlRegex = /(https?:\/\/[^\s]+)/;
    const urlMatch = content.match(urlRegex);
    if (urlMatch && urlMatch[1]) {
      return urlMatch[1];
    }
    return null;
  }
  /**
   * Transform URL using configured transformation rules
   * Returns the transformed URL or null if proxy is down
   */
  async transformUrlIfNeeded(url) {
    if (!this.urlTransformer || !this.transformationConfig) {
      return { url, originalUrl: url };
    }
    const result = await this.urlTransformer.transformUrl(
      url,
      this.transformationConfig.rules
    );
    return {
      url: result.transformedUrl,
      originalUrl: result.originalUrl,
      appliedRule: result.appliedRule,
      error: result.error
    };
  }
  /**
   * Update file frontmatter with proxy information
   */
  async updateFrontmatterWithProxyInfo(file, originalUrl, proxiedUrl, proxyRule) {
    var _a;
    try {
      const content = await this.app.vault.read(file);
      const frontMatterInfo = (0, import_obsidian3.getFrontMatterInfo)(content);
      if (!frontMatterInfo.exists) {
        const newFrontmatter = `---
original_url: ${originalUrl}
proxied_url: ${proxiedUrl}
proxy_rule: "${proxyRule}"
---

`;
        const newContent = newFrontmatter + content;
        await this.app.vault.modify(file, newContent);
      } else {
        const frontmatterText = content.substring(
          frontMatterInfo.from,
          frontMatterInfo.to
        );
        const frontmatter = (0, import_obsidian3.parseYaml)(frontmatterText);
        const updatedFrontmatter = {
          ...frontmatter,
          original_url: originalUrl,
          proxied_url: proxiedUrl,
          proxy_rule: proxyRule
        };
        const yamlLines = Object.entries(updatedFrontmatter).map(([key, value]) => this.serializeYamlValue(key, value));
        const newFrontmatter = `---
${yamlLines.join("\n")}
---
`;
        const afterFrontmatter = content.substring((_a = frontMatterInfo.contentStart) != null ? _a : frontMatterInfo.to);
        const newContent = newFrontmatter + afterFrontmatter;
        await this.app.vault.modify(file, newContent);
      }
    } catch (error) {
      console.error("Error updating frontmatter with proxy info:", error);
    }
  }
  /**
   * Process a file: extract URL and fetch article information via ReadItLater
   * Creates a new note with the article content
   */
  async processFile(file) {
    try {
      const content = await this.app.vault.read(file);
      let url = this.extractUrlFromFrontmatter(content);
      if (!url) {
        url = this.extractUrlFromContent(content);
      }
      if (!url) {
        new import_obsidian3.Notice(`No URL found in file: ${file.name}`);
        console.warn(`No URL found in file: ${file.path}`);
        return;
      }
      const transformResult = await this.transformUrlIfNeeded(url);
      if (!transformResult.url) {
        new import_obsidian3.Notice(`Proxy unavailable: ${transformResult.appliedRule}. Skipping article: ${file.name}`);
        console.warn(`Skipping ${file.path} - ${transformResult.error}`);
        return;
      }
      const urlToProcess = transformResult.url;
      new import_obsidian3.Notice(`Processing URL: ${urlToProcess}`);
      console.log(`Extracted URL from ${file.path}: ${transformResult.originalUrl}`);
      if (transformResult.appliedRule) {
        console.log(`Applied transformation: ${transformResult.appliedRule}`);
      }
      await this.readItLaterApi.processContent(urlToProcess);
      new import_obsidian3.Notice(`Successfully processed article from: ${urlToProcess}`);
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : "Unknown error";
      new import_obsidian3.Notice(`Error processing file: ${errorMessage}`);
      console.error(`Error processing file ${file.path}:`, error);
    }
  }
  /**
   * Process a file and append the retrieved article content to the existing file
   * instead of creating a new note.
   * Uses ReadItLater plugin's parser if available for better markdown generation.
   *
   * @param file - The file to process
   * @param checkProcessed - If true, checks if file was already processed (for batch operations)
   * @param minContentRatio - If provided, only append if fetched content is this many times longer than existing
   */
  async processFileAndAppend(file, checkProcessed = false, minContentRatio) {
    try {
      if (checkProcessed && await this.isFileProcessed(file)) {
        console.log(`Skipping already processed file: ${file.path}`);
        return;
      }
      const content = await this.app.vault.read(file);
      let url = this.extractUrlFromFrontmatter(content);
      if (!url) {
        url = this.extractUrlFromContent(content);
      }
      if (!url) {
        new import_obsidian3.Notice(`No URL found in file: ${file.name}`);
        console.warn(`No URL found in file: ${file.path}`);
        return;
      }
      const transformResult = await this.transformUrlIfNeeded(url);
      if (!transformResult.url) {
        new import_obsidian3.Notice(`Proxy unavailable: ${transformResult.appliedRule}. Skipping article: ${file.name}`);
        console.warn(`Skipping ${file.path} - ${transformResult.error}`);
        return;
      }
      const urlToFetch = transformResult.url;
      const originalUrl = transformResult.originalUrl;
      new import_obsidian3.Notice(`Fetching and parsing article from: ${urlToFetch}`);
      console.log(`Extracted URL from ${file.path}: ${originalUrl}`);
      if (transformResult.appliedRule) {
        console.log(`Applied transformation: ${transformResult.appliedRule}`);
      }
      const articleMarkdown = await this.readItLaterApi.getMarkdownContent(urlToFetch);
      if (!articleMarkdown) {
        new import_obsidian3.Notice(`Failed to fetch content from: ${urlToFetch}`);
        return;
      }
      if (minContentRatio !== void 0) {
        const existingBodyLength = this.getBodyContentLength(content);
        const fetchedLength = articleMarkdown.length;
        const ratio = existingBodyLength > 0 ? fetchedLength / existingBodyLength : fetchedLength;
        if (ratio < minContentRatio) {
          console.log(`Skipping ${file.path}: content ratio ${ratio.toFixed(2)} < ${minContentRatio}`);
          if (checkProcessed) {
            await this.markFileAsProcessed(file);
          }
          return;
        }
        console.log(`Processing ${file.path}: content ratio ${ratio.toFixed(2)} >= ${minContentRatio}`);
      }
      if (transformResult.appliedRule) {
        await this.updateFrontmatterWithProxyInfo(file, originalUrl, urlToFetch, transformResult.appliedRule);
      }
      const { frontmatter: fetchedFrontmatter, body: articleBody } = this.splitFrontmatter(articleMarkdown);
      if (fetchedFrontmatter && Object.keys(fetchedFrontmatter).length > 0) {
        await this.mergeFetchedFrontmatter(file, fetchedFrontmatter);
      }
      const separator = "\n\n---\n\n## Retrieved Article Content\n\n";
      const contentToAppend = separator + articleBody;
      await this.app.vault.append(file, contentToAppend);
      if (checkProcessed) {
        await this.markFileAsProcessed(file);
      }
      new import_obsidian3.Notice(`Successfully appended article content to: ${file.name}`);
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : "Unknown error";
      new import_obsidian3.Notice(`Error processing file: ${errorMessage}`);
      console.error(`Error processing file ${file.path}:`, error);
    }
  }
  /**
   * Process all files in a folder
   */
  async processFolderFiles(folderPath) {
    const files = this.app.vault.getMarkdownFiles().filter(
      (file) => file.path.startsWith(folderPath)
    );
    if (files.length === 0) {
      new import_obsidian3.Notice(`No markdown files found in: ${folderPath}`);
      return;
    }
    new import_obsidian3.Notice(`Processing ${files.length} files...`);
    for (const file of files) {
      await this.processFile(file);
    }
    new import_obsidian3.Notice(`Completed processing ${files.length} files`);
  }
  /**
   * Process current active file and create a new note
   */
  async processActiveFile() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian3.Notice("No active file found");
      return;
    }
    await this.processFile(activeFile);
  }
  /**
   * Process current active file and append content to it
   */
  async processActiveFileAndAppend() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian3.Notice("No active file found");
      return;
    }
    await this.processFileAndAppend(activeFile);
  }
  /**
   * Process all files in a folder and append content to each
   * Skips files that have already been processed (have article_processed: true)
   *
   * @param folderPath - The folder path to process
   * @param minContentRatio - If provided, only append if fetched content is this many times longer than existing
   */
  async processFolderFilesAndAppend(folderPath, minContentRatio) {
    const files = this.app.vault.getMarkdownFiles().filter(
      (file) => file.path.startsWith(folderPath)
    );
    if (files.length === 0) {
      new import_obsidian3.Notice(`No markdown files found in: ${folderPath}`);
      return;
    }
    new import_obsidian3.Notice(`Processing ${files.length} files...`);
    let processedCount = 0;
    let skippedCount = 0;
    for (const file of files) {
      const wasProcessed = await this.isFileProcessed(file);
      if (wasProcessed) {
        skippedCount++;
        continue;
      }
      await this.processFileAndAppend(file, true, minContentRatio);
      const nowProcessed = await this.isFileProcessed(file);
      if (nowProcessed) {
        processedCount++;
      } else {
        skippedCount++;
      }
    }
    new import_obsidian3.Notice(`Completed: ${processedCount} processed, ${skippedCount} skipped (already processed)`);
  }
  /**
   * Get the body content length (excluding frontmatter)
   */
  getBodyContentLength(fileContent) {
    const frontMatterInfo = (0, import_obsidian3.getFrontMatterInfo)(fileContent);
    if (frontMatterInfo.exists) {
      return fileContent.substring(frontMatterInfo.to).trim().length;
    }
    return fileContent.trim().length;
  }
  /**
   * Auto-process a file only if fetched content is significantly longer
   * than existing content. Used for scheduled background processing.
   */
  async autoProcessFileIfLonger(file, minContentRatio) {
    try {
      if (await this.isFileProcessed(file)) {
        return false;
      }
      const content = await this.app.vault.read(file);
      const existingBodyLength = this.getBodyContentLength(content);
      let url = this.extractUrlFromFrontmatter(content);
      if (!url) {
        url = this.extractUrlFromContent(content);
      }
      if (!url) {
        return false;
      }
      const transformResult = await this.transformUrlIfNeeded(url);
      if (!transformResult.url) {
        return false;
      }
      const articleMarkdown = await this.readItLaterApi.getMarkdownContent(transformResult.url);
      if (!articleMarkdown) {
        return false;
      }
      const fetchedLength = articleMarkdown.length;
      const ratio = existingBodyLength > 0 ? fetchedLength / existingBodyLength : fetchedLength;
      if (ratio >= minContentRatio) {
        if (transformResult.appliedRule) {
          await this.updateFrontmatterWithProxyInfo(file, transformResult.originalUrl, transformResult.url, transformResult.appliedRule);
        }
        const { frontmatter: fetchedFrontmatter, body: articleBody } = this.splitFrontmatter(articleMarkdown);
        if (fetchedFrontmatter && Object.keys(fetchedFrontmatter).length > 0) {
          await this.mergeFetchedFrontmatter(file, fetchedFrontmatter);
        }
        const separator = "\n\n---\n\n## Retrieved Article Content\n\n";
        await this.app.vault.append(file, separator + articleBody);
        await this.markFileAsProcessed(file);
        console.log(`Auto-processed ${file.path}: ratio ${ratio.toFixed(2)} >= ${minContentRatio}`);
        return true;
      }
      return false;
    } catch (error) {
      console.error(`Error auto-processing ${file.path}:`, error);
      return false;
    }
  }
  /**
   * Split a markdown string into frontmatter object and body content.
   * If no frontmatter delimiters are found, returns null frontmatter and the full string as body.
   */
  splitFrontmatter(markdown) {
    const trimmed = markdown.trimStart();
    if (!trimmed.startsWith("---")) {
      return { frontmatter: null, body: markdown };
    }
    const endIndex = trimmed.indexOf("---", 3);
    if (endIndex === -1) {
      return { frontmatter: null, body: markdown };
    }
    const yamlBlock = trimmed.substring(3, endIndex).trim();
    const body = trimmed.substring(endIndex + 3).trimStart();
    try {
      const parsed = (0, import_obsidian3.parseYaml)(yamlBlock);
      if (parsed && typeof parsed === "object") {
        return { frontmatter: parsed, body };
      }
    } catch (error) {
      console.warn("Failed to parse fetched article frontmatter:", error);
    }
    return { frontmatter: null, body: markdown };
  }
  /**
   * Merge fetched article metadata into the file's existing frontmatter.
   * Only adds keys that don't already exist in the file's frontmatter.
   */
  async mergeFetchedFrontmatter(file, fetchedMeta) {
    var _a;
    try {
      const content = await this.app.vault.read(file);
      const frontMatterInfo = (0, import_obsidian3.getFrontMatterInfo)(content);
      if (!frontMatterInfo.exists) {
        const yamlLines = Object.entries(fetchedMeta).map(([key, value]) => this.serializeYamlValue(key, value));
        const newFrontmatter = `---
${yamlLines.join("\n")}
---

`;
        const newContent = newFrontmatter + content;
        await this.app.vault.modify(file, newContent);
      } else {
        const frontmatterText = content.substring(
          frontMatterInfo.from,
          frontMatterInfo.to
        );
        const existingFrontmatter = (0, import_obsidian3.parseYaml)(frontmatterText) || {};
        let updated = false;
        const mergedFrontmatter = { ...existingFrontmatter };
        for (const [key, value] of Object.entries(fetchedMeta)) {
          if (!(key in mergedFrontmatter) && value !== null && value !== void 0) {
            mergedFrontmatter[key] = value;
            updated = true;
          }
        }
        if (updated) {
          const yamlLines = Object.entries(mergedFrontmatter).map(([key, value]) => this.serializeYamlValue(key, value));
          const newFrontmatter = `---
${yamlLines.join("\n")}
---
`;
          const afterFrontmatter = content.substring((_a = frontMatterInfo.contentStart) != null ? _a : frontMatterInfo.to);
          const newContent = newFrontmatter + afterFrontmatter;
          await this.app.vault.modify(file, newContent);
        }
      }
    } catch (error) {
      console.error("Error merging fetched frontmatter:", error);
    }
  }
  /**
   * Auto-process all files in a folder based on content length comparison
   */
  async autoProcessFolder(folderPath, minContentRatio) {
    const files = this.app.vault.getMarkdownFiles().filter(
      (file) => file.path.startsWith(folderPath)
    );
    let processed = 0;
    let skipped = 0;
    for (const file of files) {
      const wasProcessed = await this.autoProcessFileIfLonger(file, minContentRatio);
      if (wasProcessed) {
        processed++;
      } else {
        skipped++;
      }
    }
    return { processed, skipped };
  }
  /**
   * Batch process multiple URLs from a file
   * Expects URLs to be separated by newlines
   */
  async processUrlBatch(file) {
    try {
      const content = await this.app.vault.read(file);
      const urls = content.split("\n").map((line) => line.trim()).filter((line) => line.match(/^https?:\/\//));
      if (urls.length === 0) {
        new import_obsidian3.Notice("No URLs found in file");
        return;
      }
      new import_obsidian3.Notice(`Processing ${urls.length} URLs...`);
      const transformedUrls = [];
      const skippedUrls = [];
      const downProxies = /* @__PURE__ */ new Set();
      for (const url of urls) {
        const transformResult = await this.transformUrlIfNeeded(url);
        if (!transformResult.url) {
          if (transformResult.appliedRule && !downProxies.has(transformResult.appliedRule)) {
            downProxies.add(transformResult.appliedRule);
            new import_obsidian3.Notice(`Proxy unavailable: ${transformResult.appliedRule}. Skipping related URLs.`);
          }
          skippedUrls.push(url);
          continue;
        }
        transformedUrls.push(transformResult.url);
      }
      if (transformedUrls.length === 0) {
        new import_obsidian3.Notice("All URLs skipped due to proxy unavailability");
        return;
      }
      const urlBatch = transformedUrls.join("\n");
      await this.readItLaterApi.processContentBatch(urlBatch);
      const message = skippedUrls.length > 0 ? `Processed ${transformedUrls.length} URLs, skipped ${skippedUrls.length} due to proxy issues` : `Successfully processed ${transformedUrls.length} URLs`;
      new import_obsidian3.Notice(message);
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : "Unknown error";
      new import_obsidian3.Notice(`Error processing URL batch: ${errorMessage}`);
      console.error("Error processing URL batch:", error);
    }
  }
};

// src/url-transformer/default-templates.ts
function getDefaultTransformationRules() {
  return [
    {
      id: "freedium-medium",
      name: "Medium via Freedium",
      enabled: false,
      matchers: ["*.medium.com", "medium.com"],
      excludeMatchers: [],
      transformationType: "prefix",
      template: "https://freedium-mirror.cfd/{url}",
      priority: 100
    },
    {
      id: "12ft-ladder",
      name: "12ft Ladder (General Paywall Bypass)",
      enabled: false,
      matchers: ["*"],
      excludeMatchers: [],
      transformationType: "prefix",
      template: "https://12ft.io/{url}",
      priority: 10
    },
    {
      id: "archive-today",
      name: "Archive.today",
      enabled: false,
      matchers: ["*"],
      excludeMatchers: [],
      transformationType: "prefix",
      template: "https://archive.is/{url}",
      priority: 20
    }
  ];
}

// src/url-transformer/transformation-config.ts
var TransformationConfigManager = class {
  constructor(app, plugin) {
    this.config = null;
    this.app = app;
    this.plugin = plugin;
  }
  getDefaultAutoProcessingConfig() {
    return {
      enabled: false,
      folderPaths: [],
      frequencyMinutes: 60,
      minContentLengthRatio: 2
    };
  }
  getDefaultConfig() {
    return {
      rules: getDefaultTransformationRules(),
      enableProxyFallback: true,
      proxyHealthCacheTtlMinutes: 5,
      proxyHealthTimeoutMs: 5e3,
      autoProcessing: this.getDefaultAutoProcessingConfig()
    };
  }
  async loadConfig() {
    try {
      const loadedData = await this.plugin.loadData();
      if (!loadedData || !loadedData.transformationConfig) {
        const defaultConfig = this.getDefaultConfig();
        await this.saveConfig(defaultConfig);
        this.config = defaultConfig;
        return defaultConfig;
      }
      const loadedConfig = loadedData.transformationConfig;
      const mergedConfig = this.mergeWithDefaults(loadedConfig);
      this.config = mergedConfig;
      return mergedConfig;
    } catch (error) {
      console.error("Error loading transformation config:", error);
      const defaultConfig = this.getDefaultConfig();
      this.config = defaultConfig;
      return defaultConfig;
    }
  }
  mergeWithDefaults(loadedConfig) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l;
    const defaultRules = getDefaultTransformationRules();
    const loadedRuleIds = new Set(loadedConfig.rules.map((r) => r.id));
    const newDefaultRules = defaultRules.filter((dr) => !loadedRuleIds.has(dr.id));
    const defaultAutoProcessing = this.getDefaultAutoProcessingConfig();
    const migratedRules = [...loadedConfig.rules, ...newDefaultRules].map((rule) => {
      var _a2;
      return {
        ...rule,
        excludeMatchers: (_a2 = rule.excludeMatchers) != null ? _a2 : []
      };
    });
    return {
      rules: migratedRules,
      enableProxyFallback: (_a = loadedConfig.enableProxyFallback) != null ? _a : true,
      proxyHealthCacheTtlMinutes: (_b = loadedConfig.proxyHealthCacheTtlMinutes) != null ? _b : 5,
      proxyHealthTimeoutMs: (_c = loadedConfig.proxyHealthTimeoutMs) != null ? _c : 5e3,
      autoProcessing: {
        enabled: (_e = (_d = loadedConfig.autoProcessing) == null ? void 0 : _d.enabled) != null ? _e : defaultAutoProcessing.enabled,
        folderPaths: (_h = (_f = loadedConfig.autoProcessing) == null ? void 0 : _f.folderPaths) != null ? _h : ((_g = loadedConfig.autoProcessing) == null ? void 0 : _g.folderPath) ? [loadedConfig.autoProcessing.folderPath] : defaultAutoProcessing.folderPaths,
        frequencyMinutes: (_j = (_i = loadedConfig.autoProcessing) == null ? void 0 : _i.frequencyMinutes) != null ? _j : defaultAutoProcessing.frequencyMinutes,
        minContentLengthRatio: (_l = (_k = loadedConfig.autoProcessing) == null ? void 0 : _k.minContentLengthRatio) != null ? _l : defaultAutoProcessing.minContentLengthRatio
      }
    };
  }
  async saveConfig(config) {
    try {
      const currentData = await this.plugin.loadData() || {};
      currentData.transformationConfig = config;
      await this.plugin.saveData(currentData);
      this.config = config;
    } catch (error) {
      console.error("Error saving transformation config:", error);
      throw error;
    }
  }
  getConfig() {
    if (!this.config) {
      throw new Error("Config not loaded. Call loadConfig() first.");
    }
    return this.config;
  }
  async addRule(rule) {
    const config = this.getConfig();
    config.rules.push(rule);
    await this.saveConfig(config);
  }
  async updateRule(ruleId, updates) {
    const config = this.getConfig();
    const ruleIndex = config.rules.findIndex((r) => r.id === ruleId);
    if (ruleIndex === -1) {
      throw new Error(`Rule with id ${ruleId} not found`);
    }
    config.rules[ruleIndex] = { ...config.rules[ruleIndex], ...updates };
    await this.saveConfig(config);
  }
  async deleteRule(ruleId) {
    const config = this.getConfig();
    config.rules = config.rules.filter((r) => r.id !== ruleId);
    await this.saveConfig(config);
  }
  async toggleRule(ruleId, enabled) {
    await this.updateRule(ruleId, { enabled });
  }
  async reorderRules(ruleIds) {
    const config = this.getConfig();
    const ruleMap = new Map(config.rules.map((r) => [r.id, r]));
    const reorderedRules = ruleIds.map((id) => ruleMap.get(id)).filter((r) => r !== void 0);
    const missingRules = config.rules.filter((r) => !ruleIds.includes(r.id));
    config.rules = [...reorderedRules, ...missingRules];
    await this.saveConfig(config);
  }
};

// src/settings/url-transformer-settings.ts
var import_obsidian4 = require("obsidian");
var UrlTransformerSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin, configManager) {
    super(app, plugin);
    this.plugin = plugin;
    this.configManager = configManager;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "URL Transformation Settings" });
    this.displayAutoProcessingSettings();
    this.displayHealthCheckSettings();
    this.displayRulesList();
    this.displayAddRuleButton();
  }
  displayAutoProcessingSettings() {
    const { containerEl } = this;
    const config = this.configManager.getConfig();
    containerEl.createEl("h3", { text: "Auto Processing" });
    new import_obsidian4.Setting(containerEl).setName("Enable auto processing").setDesc("Automatically scan a folder and process files when fetched content is longer").addToggle((toggle) => toggle.setValue(config.autoProcessing.enabled).onChange(async (value) => {
      config.autoProcessing.enabled = value;
      await this.configManager.saveConfig(config);
      if (this.plugin.restartAutoProcessing) {
        this.plugin.restartAutoProcessing();
      }
    }));
    new import_obsidian4.Setting(containerEl).setName("Watch folders").setDesc("Folder paths to monitor for files with URLs");
    const foldersContainer = containerEl.createDiv({ cls: "watch-folders-container" });
    this.displayWatchFolders(foldersContainer, config);
    new import_obsidian4.Setting(containerEl).setName("Check frequency (minutes)").setDesc("How often to scan the folders for new content (5\u2013360)").addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "5";
      text.inputEl.max = "360";
      text.inputEl.step = "5";
      text.inputEl.style.width = "80px";
      text.setValue(String(config.autoProcessing.frequencyMinutes)).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num >= 5 && num <= 360) {
          config.autoProcessing.frequencyMinutes = num;
          await this.configManager.saveConfig(config);
          if (this.plugin.restartAutoProcessing) {
            this.plugin.restartAutoProcessing();
          }
        }
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Minimum content ratio").setDesc("Only append if fetched content is this many times longer than existing (e.g., 2.0 = twice as long, range: 1.5\u201310)").addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "1.5";
      text.inputEl.max = "10";
      text.inputEl.step = "0.5";
      text.inputEl.style.width = "80px";
      text.setValue(String(config.autoProcessing.minContentLengthRatio)).onChange(async (value) => {
        const num = parseFloat(value);
        if (!isNaN(num) && num >= 1.5 && num <= 10) {
          config.autoProcessing.minContentLengthRatio = num;
          await this.configManager.saveConfig(config);
        }
      });
    });
  }
  displayWatchFolders(container, config) {
    container.empty();
    const folderPaths = config.autoProcessing.folderPaths || [];
    for (let i = 0; i < folderPaths.length; i++) {
      const folderSetting = new import_obsidian4.Setting(container).addText((text) => text.setValue(folderPaths[i]).setPlaceholder("e.g., Articles or Inbox/RSS").onChange(async (value) => {
        config.autoProcessing.folderPaths[i] = value;
        await this.configManager.saveConfig(config);
      })).addButton((button) => button.setButtonText("Remove").setWarning().onClick(async () => {
        config.autoProcessing.folderPaths.splice(i, 1);
        await this.configManager.saveConfig(config);
        this.displayWatchFolders(container, config);
      }));
      folderSetting.settingEl.style.borderBottom = "none";
      folderSetting.settingEl.style.padding = "4px 0";
    }
    const addSetting = new import_obsidian4.Setting(container).addButton((button) => button.setButtonText("Add folder").setCta().onClick(async () => {
      config.autoProcessing.folderPaths.push("");
      await this.configManager.saveConfig(config);
      this.displayWatchFolders(container, config);
    }));
    addSetting.settingEl.style.borderBottom = "none";
    addSetting.settingEl.style.padding = "4px 0";
  }
  displayHealthCheckSettings() {
    const { containerEl } = this;
    const config = this.configManager.getConfig();
    containerEl.createEl("h3", { text: "Proxy Health Check" });
    new import_obsidian4.Setting(containerEl).setName("Enable proxy fallback").setDesc("When a proxy is unavailable, automatically try the next matching proxy in list order").addToggle((toggle) => toggle.setValue(config.enableProxyFallback).onChange(async (value) => {
      config.enableProxyFallback = value;
      await this.configManager.saveConfig(config);
    }));
    new import_obsidian4.Setting(containerEl).setName("Cache TTL (minutes)").setDesc("How long to cache proxy health check results (1\u201330)").addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "1";
      text.inputEl.max = "30";
      text.inputEl.step = "1";
      text.inputEl.style.width = "80px";
      text.setValue(String(config.proxyHealthCacheTtlMinutes)).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num >= 1 && num <= 30) {
          config.proxyHealthCacheTtlMinutes = num;
          await this.configManager.saveConfig(config);
        }
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Health check timeout (seconds)").setDesc("Maximum time to wait for proxy health check (1\u201310)").addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "1";
      text.inputEl.max = "10";
      text.inputEl.step = "1";
      text.inputEl.style.width = "80px";
      text.setValue(String(config.proxyHealthTimeoutMs / 1e3)).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num >= 1 && num <= 10) {
          config.proxyHealthTimeoutMs = num * 1e3;
          await this.configManager.saveConfig(config);
        }
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Test all proxies").setDesc("Check the health of all enabled proxy services").addButton((button) => button.setButtonText("Test Now").onClick(async () => {
      button.setDisabled(true);
      button.setButtonText("Testing...");
      const transformer = new UrlTransformer(
        config.proxyHealthCacheTtlMinutes,
        config.proxyHealthTimeoutMs
      );
      const results = await transformer.testAllProxies(config.rules);
      let message = "Proxy Health Check Results:\n";
      results.forEach((healthy, name) => {
        message += `
${name}: ${healthy ? "\u2713 Healthy" : "\u2717 Down"}`;
      });
      new import_obsidian4.Notice(message, 1e4);
      button.setDisabled(false);
      button.setButtonText("Test Now");
    }));
  }
  displayRulesList() {
    const { containerEl } = this;
    const config = this.configManager.getConfig();
    containerEl.createEl("h3", { text: "Transformation Rules" });
    containerEl.createEl("p", {
      text: "Rules are tried in the order shown below. Drag to reorder, or use the arrow buttons.",
      cls: "setting-item-description"
    });
    const rulesContainer = containerEl.createDiv({ cls: "url-transformer-rules" });
    if (config.rules.length === 0) {
      rulesContainer.createEl("p", {
        text: "No transformation rules configured.",
        cls: "setting-item-description"
      });
      return;
    }
    for (let i = 0; i < config.rules.length; i++) {
      this.displayRule(rulesContainer, config.rules[i], i, config.rules.length);
    }
  }
  displayRule(container, rule, index, total) {
    const ruleEl = container.createDiv({ cls: "url-transformer-rule-item" });
    ruleEl.setAttribute("draggable", "true");
    ruleEl.dataset.ruleId = rule.id;
    ruleEl.dataset.ruleIndex = String(index);
    ruleEl.addEventListener("dragstart", (e) => {
      var _a;
      ruleEl.addClass("is-dragging");
      (_a = e.dataTransfer) == null ? void 0 : _a.setData("text/plain", rule.id);
    });
    ruleEl.addEventListener("dragend", () => {
      ruleEl.removeClass("is-dragging");
      container.querySelectorAll(".drag-over").forEach((el) => el.removeClass("drag-over"));
    });
    ruleEl.addEventListener("dragover", (e) => {
      e.preventDefault();
      ruleEl.addClass("drag-over");
    });
    ruleEl.addEventListener("dragleave", () => {
      ruleEl.removeClass("drag-over");
    });
    ruleEl.addEventListener("drop", async (e) => {
      var _a;
      e.preventDefault();
      ruleEl.removeClass("drag-over");
      const draggedId = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text/plain");
      if (!draggedId || draggedId === rule.id) {
        return;
      }
      const config = this.configManager.getConfig();
      const fromIndex = config.rules.findIndex((r) => r.id === draggedId);
      const toIndex = config.rules.findIndex((r) => r.id === rule.id);
      if (fromIndex === -1 || toIndex === -1) {
        return;
      }
      const [moved] = config.rules.splice(fromIndex, 1);
      config.rules.splice(toIndex, 0, moved);
      await this.configManager.saveConfig(config);
      this.display();
    });
    const ruleSetting = new import_obsidian4.Setting(ruleEl).setName(`${index + 1}. ${rule.name}`).setDesc(this.getRuleDescription(rule));
    if (index > 0) {
      ruleSetting.addButton((button) => button.setIcon("arrow-up").setTooltip("Move up").onClick(async () => {
        await this.moveRule(index, index - 1);
      }));
    }
    if (index < total - 1) {
      ruleSetting.addButton((button) => button.setIcon("arrow-down").setTooltip("Move down").onClick(async () => {
        await this.moveRule(index, index + 1);
      }));
    }
    ruleSetting.addToggle((toggle) => toggle.setValue(rule.enabled).onChange(async (value) => {
      await this.configManager.toggleRule(rule.id, value);
      new import_obsidian4.Notice(`${rule.name} ${value ? "enabled" : "disabled"}`);
    }));
    ruleSetting.addButton((button) => button.setButtonText("Edit").onClick(() => {
      this.showEditRuleModal(rule);
    }));
    const isDefaultRule = ["freedium-medium", "12ft-ladder", "archive-today"].includes(rule.id);
    if (!isDefaultRule) {
      ruleSetting.addButton((button) => button.setButtonText("Delete").setWarning().onClick(async () => {
        await this.configManager.deleteRule(rule.id);
        new import_obsidian4.Notice(`Deleted rule: ${rule.name}`);
        this.display();
      }));
    }
  }
  async moveRule(fromIndex, toIndex) {
    const config = this.configManager.getConfig();
    const [moved] = config.rules.splice(fromIndex, 1);
    config.rules.splice(toIndex, 0, moved);
    await this.configManager.saveConfig(config);
    this.display();
  }
  getRuleDescription(rule) {
    const matchersText = rule.matchers.join(", ");
    const typeText = rule.transformationType === "prefix" ? "Prefix" : "Path Extraction";
    const excludeText = rule.excludeMatchers && rule.excludeMatchers.length > 0 ? ` | Excludes: ${rule.excludeMatchers.join(", ")}` : "";
    return `Type: ${typeText} | Matches: ${matchersText}${excludeText} | Priority: ${rule.priority}`;
  }
  displayAddRuleButton() {
    const { containerEl } = this;
    new import_obsidian4.Setting(containerEl).setName("Add custom rule").setDesc("Create a new URL transformation rule").addButton((button) => button.setButtonText("Add Rule").setCta().onClick(() => {
      this.showAddRuleModal();
    }));
  }
  showAddRuleModal() {
    const modal = new RuleEditorModal(
      this.app,
      null,
      async (rule) => {
        await this.configManager.addRule(rule);
        new import_obsidian4.Notice(`Added rule: ${rule.name}`);
        this.display();
      }
    );
    modal.open();
  }
  showEditRuleModal(rule) {
    const modal = new RuleEditorModal(
      this.app,
      rule,
      async (updatedRule) => {
        await this.configManager.updateRule(rule.id, updatedRule);
        new import_obsidian4.Notice(`Updated rule: ${updatedRule.name}`);
        this.display();
      }
    );
    modal.open();
  }
};
var RuleEditorModal = class extends import_obsidian4.Modal {
  constructor(app, rule, onSave) {
    super(app);
    this.rule = rule;
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.rule ? "Edit Rule" : "Add New Rule" });
    new import_obsidian4.Setting(contentEl).setName("Rule name").setDesc("Display name for this transformation rule").addText((text) => {
      var _a;
      this.nameInput = text.inputEl;
      text.setValue(((_a = this.rule) == null ? void 0 : _a.name) || "").setPlaceholder("e.g., Medium via Freedium");
    });
    new import_obsidian4.Setting(contentEl).setName("URL matchers (include)").setDesc("Domain patterns to match (one per line). Use * for wildcard, *.domain.com for subdomains").addTextArea((text) => {
      var _a;
      this.matchersInput = text.inputEl;
      text.setValue(((_a = this.rule) == null ? void 0 : _a.matchers.join("\n")) || "").setPlaceholder("*.medium.com\nmedium.com");
      text.inputEl.rows = 4;
    });
    new import_obsidian4.Setting(contentEl).setName("URL matchers (exclude)").setDesc("Domain patterns to exclude (one per line). URLs matching these will NOT use this proxy.").addTextArea((text) => {
      var _a, _b;
      this.excludeMatchersInput = text.inputEl;
      text.setValue(((_b = (_a = this.rule) == null ? void 0 : _a.excludeMatchers) == null ? void 0 : _b.join("\n")) || "").setPlaceholder("blog.example.com\n*.internal.com");
      text.inputEl.rows = 3;
    });
    new import_obsidian4.Setting(contentEl).setName("Transformation type").setDesc("How to transform the URL").addDropdown((dropdown) => {
      var _a;
      this.typeSelect = dropdown.selectEl;
      dropdown.addOption("prefix", "Prefix (prepend proxy URL)").addOption("path-extraction", "Path Extraction (extract and remap path)").setValue(((_a = this.rule) == null ? void 0 : _a.transformationType) || "prefix");
    });
    new import_obsidian4.Setting(contentEl).setName("Template").setDesc("URL template. Use {url} for full URL, {path} for path, {domain} for domain").addText((text) => {
      var _a;
      this.templateInput = text.inputEl;
      text.setValue(((_a = this.rule) == null ? void 0 : _a.template) || "").setPlaceholder("https://proxy.com/{url}");
    });
    new import_obsidian4.Setting(contentEl).setName("Priority").setDesc("Higher priority rules are applied first (1-1000)").addText((text) => {
      var _a;
      this.priorityInput = text.inputEl;
      text.setValue(String(((_a = this.rule) == null ? void 0 : _a.priority) || 100)).setPlaceholder("100");
      text.inputEl.type = "number";
    });
    new import_obsidian4.Setting(contentEl).addButton((button) => button.setButtonText("Cancel").onClick(() => this.close())).addButton((button) => button.setButtonText("Save").setCta().onClick(() => this.handleSave()));
  }
  handleSave() {
    var _a, _b, _c;
    const name = this.nameInput.value.trim();
    const matchersText = this.matchersInput.value.trim();
    const excludeMatchersText = this.excludeMatchersInput.value.trim();
    const template = this.templateInput.value.trim();
    const priority = parseInt(this.priorityInput.value) || 100;
    if (!name || !matchersText || !template) {
      new import_obsidian4.Notice("Please fill in all required fields");
      return;
    }
    const matchers = matchersText.split("\n").map((m) => m.trim()).filter((m) => m.length > 0);
    const excludeMatchers = excludeMatchersText ? excludeMatchersText.split("\n").map((m) => m.trim()).filter((m) => m.length > 0) : [];
    if (matchers.length === 0) {
      new import_obsidian4.Notice("Please provide at least one URL matcher");
      return;
    }
    const rule = {
      id: ((_a = this.rule) == null ? void 0 : _a.id) || `custom-${Date.now()}`,
      name,
      enabled: (_c = (_b = this.rule) == null ? void 0 : _b.enabled) != null ? _c : true,
      matchers,
      excludeMatchers,
      transformationType: this.typeSelect.value,
      template,
      priority
    };
    this.onSave(rule);
    this.close();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/plugin-main.ts
var MetadataLinkParserPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.autoProcessingIntervalId = null;
  }
  createParser() {
    const parser = new MetadataLinkParser(this.app, this.noteService);
    parser.setTransformationConfig(this.configManager.getConfig());
    return parser;
  }
  async onload() {
    console.log("Loading Metadata Link Parser Plugin");
    this.noteService = getNoteService(this.app);
    this.configManager = new TransformationConfigManager(this.app, this);
    await this.configManager.loadConfig();
    this.addSettingTab(new UrlTransformerSettingTab(this.app, this, this.configManager));
    if (isReadItLaterInstalled(this.app)) {
      console.log("Metadata Link Parser: Using ReadItLater plugin");
    } else {
      console.log("Metadata Link Parser: Using built-in stub implementation");
    }
    this.addCommand({
      id: "parse-active-file-link",
      name: "Parse link from active file (create new note)",
      callback: async () => {
        const parser = this.createParser();
        await parser.processActiveFile();
      }
    });
    this.addCommand({
      id: "parse-active-file-link-append",
      name: "Parse link and append to active file",
      callback: async () => {
        const parser = this.createParser();
        await parser.processActiveFileAndAppend();
      }
    });
    this.addCommand({
      id: "parse-folder-links",
      name: "Parse links from folder (create new notes)",
      callback: async () => {
        const folderPath = "Articles";
        const parser = this.createParser();
        await parser.processFolderFiles(folderPath);
      }
    });
    this.addCommand({
      id: "parse-folder-links-append",
      name: "Parse links from folder and append to files",
      callback: async () => {
        const folderPath = "Articles";
        const parser = this.createParser();
        const config = this.configManager.getConfig();
        await parser.processFolderFilesAndAppend(folderPath, config.autoProcessing.minContentLengthRatio);
      }
    });
    this.addCommand({
      id: "batch-process-urls",
      name: "Batch process URLs from file",
      callback: async () => {
        const activeFile = this.app.workspace.getActiveFile();
        if (!activeFile) {
          return;
        }
        const parser = this.createParser();
        await parser.processUrlBatch(activeFile);
      }
    });
    this.addRibbonIcon("link", "Parse link and append to file", async () => {
      const parser = this.createParser();
      await parser.processActiveFileAndAppend();
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian5.TFolder) {
          menu.addItem((item) => {
            item.setTitle("Append articles to files in folder").setIcon("link").onClick(async () => {
              const parser = this.createParser();
              const config = this.configManager.getConfig();
              await parser.processFolderFilesAndAppend(file.path, config.autoProcessing.minContentLengthRatio);
            });
          });
          menu.addItem((item) => {
            item.setTitle("Create notes from links in folder").setIcon("file-plus").onClick(async () => {
              const parser = this.createParser();
              await parser.processFolderFiles(file.path);
            });
          });
        }
        if (file instanceof import_obsidian5.TFile) {
          menu.addItem((item) => {
            item.setTitle("Append article to this file").setIcon("link").onClick(async () => {
              const parser = this.createParser();
              await parser.processFileAndAppend(file);
            });
          });
          menu.addItem((item) => {
            item.setTitle("Create note from link").setIcon("file-plus").onClick(async () => {
              const parser = this.createParser();
              await parser.processFile(file);
            });
          });
        }
      })
    );
    this.startAutoProcessing();
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        if (view instanceof import_obsidian5.MarkdownView && view.file) {
          const file = view.file;
          menu.addItem((item) => {
            item.setTitle("Append article to this file").setIcon("link").onClick(async () => {
              const parser = this.createParser();
              await parser.processFileAndAppend(file);
            });
          });
          menu.addItem((item) => {
            item.setTitle("Create note from link").setIcon("file-plus").onClick(async () => {
              const parser = this.createParser();
              await parser.processFile(file);
            });
          });
        }
      })
    );
  }
  startAutoProcessing() {
    const config = this.configManager.getConfig();
    const folders = config.autoProcessing.folderPaths.filter((f) => f.trim().length > 0);
    if (!config.autoProcessing.enabled || folders.length === 0) {
      return;
    }
    const intervalMs = config.autoProcessing.frequencyMinutes * 60 * 1e3;
    console.log(`Auto-processing enabled: checking [${folders.join(", ")}] every ${config.autoProcessing.frequencyMinutes} minutes`);
    this.autoProcessingIntervalId = window.setInterval(async () => {
      await this.runAutoProcessing();
    }, intervalMs);
    this.registerInterval(this.autoProcessingIntervalId);
  }
  stopAutoProcessing() {
    if (this.autoProcessingIntervalId !== null) {
      window.clearInterval(this.autoProcessingIntervalId);
      this.autoProcessingIntervalId = null;
    }
  }
  restartAutoProcessing() {
    this.stopAutoProcessing();
    this.startAutoProcessing();
  }
  async runAutoProcessing() {
    const config = this.configManager.getConfig();
    const folders = config.autoProcessing.folderPaths.filter((f) => f.trim().length > 0);
    if (!config.autoProcessing.enabled || folders.length === 0) {
      return;
    }
    const parser = this.createParser();
    let totalProcessed = 0;
    let totalSkipped = 0;
    for (const folderPath of folders) {
      console.log(`Running auto-processing for folder: ${folderPath}`);
      const result = await parser.autoProcessFolder(
        folderPath,
        config.autoProcessing.minContentLengthRatio
      );
      totalProcessed += result.processed;
      totalSkipped += result.skipped;
    }
    if (totalProcessed > 0) {
      console.log(`Auto-processing complete: ${totalProcessed} files updated, ${totalSkipped} skipped`);
    }
  }
  onunload() {
    this.stopAutoProcessing();
    console.log("Unloading Metadata Link Parser Plugin");
  }
};
